trainingInput:
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: accuracy
    maxTrials: 4
    maxParallelTrials: 2
    params:
      - parameterName: squeeze_param
        type: INTEGER
        minValue: 16
        maxValue: 64
        scaleType: UNIT_LINEAR_SCALE