trainingInput:
  hyperparameters:
    goal: MAXIMIZE
    hyperparameterMetricTag: accuracy
    maxTrials: 20
    maxParallelTrials: 1
    params:
      - parameterName: kernel_size
        type: INTEGER
        minValue: 3
        maxValue: 6
        scaleType: UNIT_REVERSE_LOG_SCALE
      - parameterName: filters
        type: INTEGER
        minValue: 5
        maxValue: 20
        scaleType: UNIT_REVERSE_LOG_SCALE
      - parameterName: top_neurons
        type: INTEGER
        minValue: 16
        maxValue: 84
        scaleType: UNIT_REVERSE_LOG_SCALE
      - parameterName: dropout
        type: DOUBLE
        minValue: 0.1
        maxValue: 0.6
        scaleType: UNIT_REVERSE_LOG_SCALE
      - parameterName: squeeze_param
        type: INTEGER
        minValue: 2
        maxValue: 8
        scaleType: UNIT_REVERSE_LOG_SCALE
      - parameterName: bottleneck
        type: INTEGER
        minValue: 8
        maxValue: 128
        scaleType: UNIT_REVERSE_LOG_SCALE
      - parameterName: squeeze_ratio
        type: DOUBLE
        minValue: 0.1
        maxValue: 0.7
        scaleType: UNIT_REVERSE_LOG_SCALE
      - parameterName: pct_3x3
        type: DOUBLE
        minValue: 0.15
        maxValue: 0.75
        scaleType: UNIT_REVERSE_LOG_SCALE
